---
apiVersion: v1
kind: Service
metadata:
  name: jacksont-test-redis-service
  labels:
    username: jacksont
    env: test
spec:
  type: ClusterIP
  selector:
    app: jacksont-test-redis-deployment
  ports:
  - name: redis
    port: 6379
    targetPort: 6379