---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jacksont-test-redis-deployment
  labels:
    app: jacksont-test-redis-deployment
    username: jacksont
    env: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jacksont-test-redis-deployment
      username: jacksont
      env: test
  template:
    metadata:
      labels:
        app: jacksont-test-redis
        username: jacksont
        env: test
    spec:
      containers:
        - name: jacksont-test-redis-deployment
          imagePullPolicy: Always
          image: redis:7
          command: ['sh', '-c', 'echo "Hello, Kubernetes!" >> /data/out.txt && sleep 3600']
          volumeMounts:
          - name: jacksont-app-data
            mountPath: "/data"
      volumes:
      - name: jacksont-app-data
        persistentVolumeClaim:
          claimName: jacksont-app-data