---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jacksont-app-data
  labels:
    username: jacksont
    env: test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: cinder-csi
  resources:
    requests:
      storage: 1Gi